// Code generated by Slice Machine — update as needed.

import type * as prismic from "@prismicio/client";

// ─── Job Offer ────────────────────────────────────────────────────────────────

export interface JobOfferDocumentDataTagsItem {
  tag: prismic.KeyTextField;
}

export interface JobOfferDocumentDataAdminEmailsItem {
  email: prismic.KeyTextField;
}

export interface JobOfferDocumentData {
  title: prismic.TitleField;
  date: prismic.DateField;
  tags: prismic.GroupField<JobOfferDocumentDataTagsItem>;
  description: prismic.RichTextField;
  admin_emails: prismic.GroupField<JobOfferDocumentDataAdminEmailsItem>;
}

export type JobOfferDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<JobOfferDocumentData, "job_offer", Lang>;

// ─── Mentions Légales ─────────────────────────────────────────────────────────

export interface MentionsDocumentData {
  content: prismic.RichTextField;
}

export type MentionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<MentionsDocumentData, "mentions", Lang>;

// ─── All document types ───────────────────────────────────────────────────────

export type AllDocumentTypes = JobOfferDocument | MentionsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
}
